### ISSUE TITLE
Add isCollapse parameter

### ISSUE THREAD

**Issue by keanallen** [RyuuKenshi/flutter_collapsible_sidebar#18]
We should be able to set  the collapse behaviour conditionally by setting `isCollapse` to `true or false`

**Comment by RyuuKenshi** [comment]
There is no `isCollapse` parameter by default. 
Normally this widget is used for navigation hence the control to collapse or not to collapse is given to the user.

If you want to add the feature of being able to programatically  change the collapse behavior, you can open a PR.
This project is always open to contributions.

**Comment by RyuuKenshi** [comment]
Hi @keanallen, I have updated the package (v2.0.1+1).
Now you can configure if the sidebar is collapsed or expanded initially by changing the `isCollapsed` parameter.
Hope I could have helped.
