### ISSUE TITLE
Add elevation parameter

### ISSUE THREAD

**Issue by keanallen** [RyuuKenshi/flutter_collapsible_sidebar#19]
We should also be able to set elevation

**Comment by RyuuKenshi** [comment]
Hi @keanallen, I have updated the package (v2.0.1+1). 
Under the hood CollapsibleSidebar implements a Container so I have made it such that you can configure the shadow of the sidebar using a new parameter called `sidebarBoxShadow`. It works same as the `boxShadow` parameter of the `BoxDecoration` parameter of a "Container".
This way you can change both the elevation as well as the color of the shadow of the sidebar.

**Comment by keanallen** [comment]
Thank you! I was supposed to make my own collapsible today, but no need because you updated your package.

Thanks!

**Comment by RyuuKenshi** [comment]
No problem 😁.
Always happy to help.
