### ISSUE TITLE
Not clickable in between label/icon (web)

### ISSUE THREAD

**Issue by wottpal** [RyuuKenshi/flutter_collapsible_sidebar#4]
Hey, this is a really great package! Thanks!

If I click inside the red highlighted areas nothing happens on the web (not tested on mobile). 
<img width="268" alt="Bildschirmfoto 2020-10-12 um 01 19 52" src="https://user-images.githubusercontent.com/3930150/95692867-3fe38580-0c29-11eb-954a-853dc4a27624.png">

**Comment by RyuuKenshi** [comment]
Thanks a lot for pointing out that error. Will fix it as soon as possible in the next update.
A bit busy at the moment due to exams but surely will fix it by the end of this month.

**Comment by RyuuKenshi** [comment]
You too can try to fix it and contribute to this project. Just fork my project and create a pull request. I'll definitely merge it if it solves the problem.

**Comment by RyuuKenshi** [comment]
Hi @wottpal,

Extremely sorry for the delay. I have fixed the bug and also added some new features with version `v1.0.7+2`.

Do check out the new version at [https://pub.dev/packages/collapsible_sidebar](url).

Also do check the updated web example at [https://ryuukenshi.github.io/collapsible_sidebar](url).
