### ISSUE TITLE
Scrolling menu for multiple tabs

### ISSUE THREAD

**Issue by Hijodelalunah** [RyuuKenshi/flutter_collapsible_sidebar#5]
When you add multiple items to the list you get pixels overflow error
I made a little change here : 

https://github.com/RyuuKenshi/flutter_collapsible_sidebar/blob/00f5e8fa929ea05e5dcc9da3362e59f7a90ca278/lib/collapsible_sidebar.dart#L172-L184

So now it looks like 

```
                    Stack(
                      children: [
                        /**
                        CollapsibleItemSelection(
                          height: _maxOffsetY,
                          offsetY: _maxOffsetY * _selectedItemIndex,
                          color: widget.selectedIconBox,
                          duration: widget.duration,
                          curve: widget.curve,
                        ),*/

                        ConstrainedBox(
                          constraints: BoxConstraints(maxHeight: MediaQuery.of(context).size.height / 3),
                          child: ListView.builder(
                          itemCount: _items.length,
                          shrinkWrap: true,
                          itemBuilder: (BuildContext context, int index) {
                          return _items[index];
                          }
                          ),
                        ),
                      ],
                    ),
```
I commented the selected item highlighting because it doesn't scroll with the list so if you have better answers that would be great !

**Comment by RyuuKenshi** [comment]
Hi @Hijodelalunah, 

Thank you very much for pointing out this mistake of mine.

I saw the changes you suggested. Your changes are not making the selected item highlighting scroll, hence I did not use it as it is but used a modified version of that. 

The code I changed also enabled the highlighting to scroll. Do check it once:
`
Expanded(
                    child: SingleChildScrollView(
                      physics: BouncingScrollPhysics(),
                      reverse: widget.fitItemsToBottom,
                      child: Stack(
                        children: [
                          CollapsibleItemSelection(
                            height: _maxOffsetY,
                            offsetY: _maxOffsetY * _selectedItemIndex,
                            color: widget.selectedIconBox,
                            duration: widget.duration,
                            curve: widget.curve,
                          ),
                          Column(
                            children: _items,
                          ),
                        ],
                      ),
                    ),
                  ),
`
Also do checkout the new features I added at [https://pub.dev/packages/collapsible_sidebar](url)

**Comment by RyuuKenshi** [comment]
Hi @Hijodelalunah,

Thank you very much for pointing out this mistake of mine.

I saw the changes you suggested. Your changes are not making the selected item highlighting scroll, hence I did not use it as it is but used a modified version of that.

The code I changed also enabled the highlighting to scroll. Do check it once:
```
Expanded(
                    child: SingleChildScrollView(
                      physics: BouncingScrollPhysics(),
                      reverse: widget.fitItemsToBottom,
                      child: Stack(
                        children: [
                          CollapsibleItemSelection(
                            height: _maxOffsetY,
                            offsetY: _maxOffsetY * _selectedItemIndex,
                            color: widget.selectedIconBox,
                            duration: widget.duration,
                            curve: widget.curve,
                          ),
                          Column(
                            children: _items,
                          ),
                        ],
                      ),
                    ),
                  ),
```
Also do checkout the new features I added at https://pub.dev/packages/collapsible_sidebar

**Comment by Hijodelalunah** [comment]
Very nice work, such a creative answer 👏👏.

**Comment by RyuuKenshi** [comment]
Thanks a lot @Hijodelalunah. 
Will try to update this package as much as possible and make it the most customizable collapsible sidebar for Flutter.
